In [4]:
import statistics as st
X=[10,20,30,40,35,40,40,50,50]
print(st.mean(X))


35


In [6]:
#using pandas
import pandas as pd
x_=pd.DataFrame(X)
print(x_.mean())

0    35.0
dtype: float64


In [7]:

print(x_.median())

0    40.0
dtype: float64


In [8]:
print(x_.mode())

    0
0  40


In [1]:
#discriptive statistics
#1)central tendancy
import numpy as np
import pandas as pd
x=np.random.randint(30,35,10) #mean
print(np.mean(x))
print(np.median(x))

32.1
32.5


In [3]:
#variance (var)=means of squared deviations (below)
print('variance=', np.var(x))

variance= 0.8899999999999999


In [13]:
#standard deviation (std)= square root of variance
print('std. deviation is',np.std(x))


std. deviation is 1.3416407864998738


In [14]:
#quartiles
y=[10,20,30,40,50,60,70,80]
y_=pd.DataFrame(y)
y_.describe()

0
count   8.000000
mean   45.000000
std    24.494897
min    10.000000
25%    27.500000
50%    45.000000
75%    62.500000
max    80.000000

In [18]:
#Hypothesis
import pandas as pd
hyp=pd.read_csv() # file name path which is Available
hyp.head()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [1]:
import scipy.stats as st


In [4]:
mu=494
std=100
x=700
st.norm.cdf(x,loc=mu,scale=std)

0.9803007295906231

In [5]:
import numpy as np
#mu=220,sigma=15,n=100,mean=217 calculate propability of less than 217 mean value
st.norm.cdf(217,loc=220,scale=1.5)

0.022750131948179195

In [6]:
st.norm.cdf(6,loc=5.5,scale=0.8)

0.7340144709512995

**Numpy Study**

In [8]:
import numpy as np
np.array([5,9,13])  #converting list to array


array([ 5,  9, 13])

In [7]:
type([5,9,13])

list

In [4]:
#2 dimension array
a=np.array([[1,2],[3,4],[4,5]])
print("Type-", a.dtype)
print('\n','*'*30)
print('\n',a)

Type- int32

 ******************************

 [[1 2]
 [3 4]
 [4 5]]


In [5]:
#dtype conversion
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [15]:
#creating array using.mat(matrix)
np.array(np.mat('123 2 3;3 4.5 5;6 7 8'))   

array([[123. ,   2. ,   3. ],
       [  3. ,   4.5,   5. ],
       [  6. ,   7. ,   8. ]])

In [17]:
#convert a list into an array
a=[1,2]
c=np.array(a)
print(c)

[1 2]


In [18]:
#copy array into other
b=np.asarray(c)
print(b)

[1 2]


In [19]:
#numpy datatype
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type/class of this object:",type(mat))
print("here is the matrix\n------\n",mat,"\n------")
print("Dimension of this matrix:",mat.ndim,sep='')  #2 for a matrix , 1 for a vector
print("size of this matrix:",mat.size,sep='') #separator for matrix is space here 
print("shape of this matrix:",mat.shape)
print("Datatype of this matrix:",mat.dtype)

Type/class of this object: <class 'numpy.ndarray'>
here is the matrix
------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
------
Dimension of this matrix:2
size of this matrix:9
shape of this matrix: (3, 3)
Datatype of this matrix: int32


In [23]:
list(range(2,11,4))  #this is range we need to learn arange

[2, 6, 10]

In [25]:
a=np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [26]:
#reverse order
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [28]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,0,-5))
    

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [30]:
print("linearly spaced numbers between 1 & 5 \n _______")
print(np.linspace(10,40,5))

linearly spaced numbers between 1 & 5 
 _______
[10.  17.5 25.  32.5 40. ]


In [31]:
#include end points & check space between points
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [2]:
#Numpy matrix reshape
import numpy as np
print("vector of zeroes\n_______")
print(np.zeros(5))

vector of zeroes
_______
[0. 0. 0. 0. 0.]


In [7]:
print("matrix of zeroes\n_____")
print(np.zeros((5,6)))  #notice tuples

matrix of zeroes
_____
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
print("matrix of ones\n_______")
print(np.ones((5,8)))

matrix of ones
_______
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
print("Matrix of 2's \n_____")
print(2*np.ones((10,5)))

Matrix of 5's 
_____
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [10]:
#construct diagonal matrix
x=np.arange(30).reshape(3,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [59]:
#random number generation
np.random.seed(5) #each seed no. will generate similar data
print("random number generation( from uniform distribution)")
print(np.random.rand(10,6))

random number generation( from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


In [87]:
#random number generation
np.random.seed(95126) #each seed no. will generate similar data
print("random number generation( from uniform distribution)")
print(np.random.rand(10,6))

random number generation( from uniform distribution)
[[0.78265526 0.72080316 0.34198386 0.11534641 0.38938113 0.2316572 ]
 [0.80206735 0.69845681 0.11128263 0.43981294 0.82648266 0.34691491]
 [0.14423387 0.56230398 0.33304885 0.18705521 0.81719764 0.86919116]
 [0.71755384 0.77032758 0.34151955 0.35767453 0.76628098 0.26672425]
 [0.29505753 0.57707801 0.040345   0.12405425 0.25085835 0.08065423]
 [0.3299322  0.49326275 0.80882307 0.05465675 0.3948353  0.76718496]
 [0.99838359 0.64876283 0.05008532 0.88328289 0.04944446 0.58370364]
 [0.88589173 0.72076414 0.3645911  0.68423226 0.26215142 0.16363686]
 [0.43837095 0.54713014 0.46617746 0.31202697 0.56421211 0.69594373]
 [0.86844099 0.44838042 0.91672192 0.85729289 0.30175819 0.54497306]]


In [82]:
print("random number generation( from uniform distribution)")
print(np.random.rand(2,3))  #each execution nos will change beacuse seed is not given

random number generation( from uniform distribution)
[[0.58850006 0.60500431 0.35478546]
 [0.77738199 0.60460331 0.30923077]]


In [15]:
print("Numbers from normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(10,3))

Numbers from normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.13934298  0.4944404  -0.33633626]
 [-0.10061435  1.41339802  0.22125412]
 [-1.31077313 -0.68956523 -0.57751323]
 [ 1.15220477 -0.10716398  2.26010677]
 [ 0.65661947  0.12480683 -0.43570392]
 [ 0.97217931 -0.24071114 -0.82412345]
 [ 0.56813272  0.01275832  1.18906073]
 [-0.07359332 -2.85968797  0.7893664 ]
 [-1.87774088  1.53875615  1.82136474]
 [-0.42703139 -1.16470191 -1.39707402]]


In [99]:
print("random integer vector:",np.random.randint(5,20,10))
#r and int (low,high,#of samples to be drawn)

random integer vector: [12 18 15  8  6 13 12  9 19 13]


In [104]:
print("\nrandom integer matrix")
print(np.random.randint(1,30,(6,7)))
#randint (low,high, nos of samples to be drawn in a tuple to form a matrix)



random integer matrix
[[ 6 27  6 17 18 26  6]
 [ 1 14 20 22 29  4  3]
 [29 22 19  1 23  6 22]
 [ 6  6  4  6 20 13 22]
 [19  4 21  7  4 18  1]
 [26 27 28  8 10 23 17]]


In [105]:
#Numpy-condition
#random integer
a=np.random.randint(1,40,10)
a

array([20,  2, 23, 28, 19, 30, 38, 10, 34,  9])

In [112]:
#replace data with fixed numbers
np.clip(a,a_min=10,a_max=25)

array([20, 10, 23, 25, 19, 25, 25, 10, 25, 10])

In [113]:
#it gives index details
print(np.where(a<10))

(array([1, 9], dtype=int64),)


In [114]:
#find if data exists in the array
print(np.where(a==38))

(array([6], dtype=int64),)


In [34]:
import numpy as np
from numpy.random import randint as ri
a=ri(1,99,30)
a

array([64, 82, 23, 11, 47, 86, 84,  9, 55, 60, 12, 12, 62,  9, 38, 42, 22,
       89, 95, 46, 13, 88, 71, 32, 56, 30, 39, 80, 89,  7])

In [126]:
b =a.reshape(2,3,5)
b

array([[[87, 70, 62, 35, 54],
        [53, 92, 77, 49, 90],
        [62, 92, 20, 97, 21]],

       [[49, 33, 18, 45, 15],
        [54, 70, 19, 39, 83],
        [93, 12, 79, 71, 13]]])

In [127]:
c=a.reshape(6,5)
c

array([[87, 70, 62, 35, 54],
       [53, 92, 77, 49, 90],
       [62, 92, 20, 97, 21],
       [49, 33, 18, 45, 15],
       [54, 70, 19, 39, 83],
       [93, 12, 79, 71, 13]])

In [128]:
print("Min of a:",c.min())

Min of a: 12


In [130]:
print("Max of b:",c.max())

Max of b: 97


In [134]:
M=ri(1,100,25).reshape(5,5) 
#Matrix of random integers
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",np.sort(M))
#DEFAULT axis=1
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M))
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[23 42 74 87 91]
 [ 6 11 25 40 48]
 [14 20 42 76 83]
 [15 39 55 63 64]
 [ 9 10 25 28 93]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[23 42 74 87 91]
 [ 6 11 25 40 48]
 [14 20 42 76 83]
 [15 39 55 63 64]
 [ 9 10 25 28 93]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[25  9 10  6 20]
 [25 11 14 23 40]
 [42 15 42 28 55]
 [64 74 48 39 91]
 [87 83 63 76 93]]


In [16]:
#Indexing and slicig

arr=np.arange(13,30)
print("Array:",arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [4]:
print("Elementcat 7th index is:",arr[7])

Elementcat 7th index is: 20


In [6]:
print("elements from 3rd to 5th index are:",arr[3:6])

elements from 3rd to 5th index are: [16 17 18]


In [7]:
print("elements from 4th index are:",arr[4:])
abc=arr[4:]

elements upto 4th index are: [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [9]:
print("elements upto 4th index are:",arr[:4])


elements upto 4th index are: [13 14 15 16]


In [10]:
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
print("Elements from last backwards are:",arr[-1::-2])

Elements from last backwards are: [29 27 25 23 21 19 17 15 13]


In [12]:
print("7 Elements from last backwards are:",arr[-1:-8:-1])

7 Elements from last backwards are: [29 28 27 26 25 24 23]


In [18]:
arr=np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [19]:
print("Elements at 2nd,4th and 9th index are:",arr[[2,4,9]])

Elements at 2nd,4th and 9th index are: [ 4  8 18]


In [20]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
print("\nDouble bracket indexing\n--------")
print("Element in row index 1 and column index 2:",mat[1][2])  #matrix index start with 0,1,2,---- 


Double bracket indexing
--------
Element in row index 1 and column index 2: 6


In [22]:
print("Entire row at index 2:", mat[2])
print("\nEntire column at index 3:\n",mat[:,1:])

Entire row at index 2: [7 8 9]

Entire column at index 3:
 [[2 3]
 [5 6]
 [8 9]]


In [24]:
print("\n subletting sub-matrices \n-------")
print("Matrix with row indices 1 and 2 and column indices 1 and 2\n", mat[1:2,1:2])  #last written index is not inclusive when index numbers are written last index will not print


 subletting sub-matrices 
-------
Matrix with row indices 1 and 2 and column indices 1 and 2
 [[5]]


In [25]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print("",mat[0:2,[1,2]])   #first is row index range(in range last index is not added and second is column index values set directly written

 [[2 3]
 [5 6]]


In [33]:
#Update Matrix
mat[0][1]=35
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [2]:
#Subsetting
import numpy as np
from numpy.random import randint as ri

mat=np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers \n---------\n",mat)

Matrix of random 2-digit numbers 
---------
 [[76 45 92 16 31]
 [51 17 93 77 10]
 [79 37 19 42 71]]


In [40]:
xyz=mat[mat>70]
xyz

array([86, 95, 84, 74])

In [41]:
print("Elements greater than 50\n",mat[mat>50])

Elements greater than 50
 [59 86 95 69 55 84 74 56]


In [42]:
mat>50

array([[False,  True, False,  True,  True],
       [False,  True,  True,  True, False],
       [False, False,  True,  True, False]])

In [44]:
print(np.where(mat==55))

(array([1], dtype=int64), array([2], dtype=int64))


In [5]:
#Universal Functions

mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n1st Matrix of random digit numbers\n____________\n",mat1)

print("\n2nd Matrix of random digit numbers\n____________\n",mat2)


1st Matrix of random digit numbers
____________
 [[8 4 5]
 [6 5 5]
 [2 7 2]]

2nd Matrix of random digit numbers
____________
 [[9 7 7]
 [2 9 7]
 [5 5 5]]


In [6]:
print("\nAddition\n____________\n",mat1+mat2)


Addition
____________
 [[17 11 12]
 [ 8 14 12]
 [ 7 12  7]]


In [7]:
print("\nMultiplication\n____________\n",mat1*mat2)


Multiplication
____________
 [[72 28 35]
 [12 45 35]
 [10 35 10]]


In [8]:
print("\nDivision\n____________\n",mat1/mat2)


Division
____________
 [[0.88888889 0.57142857 0.71428571]
 [3.         0.55555556 0.71428571]
 [0.4        1.4        0.4       ]]


In [12]:
print("\Linear Combination (3 A-2 B)\n____________\n",(3*mat1-2*mat2))

\Linear Combination (3 A-2 B)
____________
 [[ 6 -2  1]
 [14 -3  1]
 [-4 11 -4]]


In [14]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,8)).reshape(4,2)

print("\n1st Matrix of random digit numbers\n____________\n",mat1)

print("\n2nd Matrix of random digit numbers\n____________\n",mat2)


1st Matrix of random digit numbers
____________
 [[7 8 8]
 [8 7 3]
 [1 9 8]]

2nd Matrix of random digit numbers
____________
 [[2 8]
 [8 1]
 [2 5]
 [5 6]]


In [15]:
print("\nAddition\n____________\n",mat1+mat2)

ValueError: operands could not be broadcast together with shapes (3,3) (4,2) 

In [ ]:
#Broadcasting
#Numpy operations are usually done on pair pf arrays on an element by element wise
#In the simplest case, 2 arrays must have exact same shape.
#Numpy's broadcasting rules relaxes this constraints, when array's shape meets with certain constraints.
#When operating of 2 arrays , Numpy compare their shape element wise. it starts with the trailing.
#Dimensions. and works its way forward.
#2 Dimensions are compatible when they are equal or one of them is 1

In [19]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#Create rank 1 ndarray with 3 values
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [22]:
#add to each row of 'start' using broadcasting
y= start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [24]:
new_row=add_rows.T   #Transpose of the matrix
new_row

array([[1],
       [0],
       [2]])

In [25]:
test=new_row+start
test

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

In [26]:
#create an ndarray which is 4 x1 to broadcast across columns
add_cols= np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [28]:
#Array Math

mat1=np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random digit numbers\n____________\n",mat1)



1st Matrix of random digit numbers
____________
 [[6 3 4]
 [8 6 8]
 [4 8 5]]


In [27]:
print("\nSquare root of matrix 1\n----------\n",np.sqrt(mat1))


Square root of matrix 1
----------
 [[2.64575131 2.82842712 2.82842712]
 [2.82842712 2.64575131 1.73205081]
 [1.         3.         2.82842712]]


In [32]:
print("\nSquare of matrix 1\n",'-'*50,"\n",np.square(mat1))


Square of matrix 1
 -------------------------------------------------- 
 [[36  9 16]
 [64 36 64]
 [16 64 25]]


**[Explore more functions] #Esc +M to write within input and output - code ==> Markdown** 

In [34]:
import numpy
print(dir(numpy))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [37]:
ar=np.array([1,2])
ar=ar+1
ar

array([2, 3])

In [39]:
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [40]:
a=np.array([1,2,3,5,8])
print(a.ndim)

1


#**Pandas Study**

In [6]:
import numpy as np
import pandas as pd

In [47]:
ser=pd.Series()
ser
print('{}\n',format(ser))

{}
 Series([], dtype: object)


In [5]:
ser=pd.Series([0,10,20,30,40,50,60,70,80,90])
print(ser)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [6]:
ser

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64

In [7]:
#Notice Datatype
ser=pd.Series([20,15.7,'10'])
ser

0      20
1    15.7
2      10
dtype: object

In [9]:
#create dictionary
dict={'A':[1,2,5],'B':[5,8,9],'C':[1,2,3]}
dict

{'A': [1, 2, 5], 'B': [5, 8, 9], 'C': [1, 2, 3]}

In [10]:
df=pd.DataFrame(dict)
df

A  B  C
0  1  5  1
1  2  8  2
2  5  9  3

In [11]:
#add new column and add values into it 
df['States']="CA NV AZ".split()
df

A  B  C States
0  1  5  1     CA
1  2  8  2     NV
2  5  9  3     AZ

In [13]:
#how to create NaN values and its manipulation
dict={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df=pd.DataFrame(dict)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [18]:
df['D']=[20,30,40]
print(df)

     A    B  C   D
0  1.0  5.0  1  20
1  2.0  NaN  2  30
2  NaN  NaN  3  40


In [19]:
print("\nDropping any column with a NaN value\n",'-'*35,sep='')
print(df.dropna(axis=1))


Dropping any column with a NaN value
-----------------------------------
   C   D
0  1  20
1  2  30
2  3  40


In [20]:
df

A    B  C   D
0  1.0  5.0  1  20
1  2.0  NaN  2  30
2  NaN  NaN  3  40

In [22]:
print("\nDropping any rows with a NaN values\n",'-'*35)
print(df.dropna(axis=0))


Dropping any rows with a NaN values
 -----------------------------------
     A    B  C   D
0  1.0  5.0  1  20


In [27]:
df  #dataframe remains same , we can save dataFrame 

A    B  C   D
0  1.0  5.0  1  20
1  2.0  NaN  2  30
2  NaN  NaN  3  40

In [32]:
print("\nFilling NaN values with a default value\n",'-'*35,sep='')
print(df.fillna(value=50))


Filling NaN values with a default value
-----------------------------------
     A    B  C   D
0  1.0  5.0  1  20
1  2.0  2.0  2  30
2  2.0  2.0  3  40


In [38]:
print("\n Filing values with a computed value(mean of column A) here\n",'-'*60,sep='')
print(df.fillna(value=df['C'].mean()))


 Filing values with a computed value(mean of column A) here
------------------------------------------------------------
     A    B  C   D
0  1.0  5.0  1  20
1  2.0  2.0  2  30
2  2.0  2.0  3  40


In [45]:
print("\n Filing values with a computed value(mean of column A) here\n",'-'*60,sep='')
print(df.fillna(value=df['C'].mean(),inplace=True))


 Filing values with a computed value(mean of column A) here
------------------------------------------------------------
None


In [46]:
df

A    B  C   D
0  1.0  5.0  1  20
1  2.0  2.0  2  30
2  2.0  2.0  3  40

In [23]:
#group by 
data={'company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
      'person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
      'Sales':[200,120,340,124,243,350]}

df=pd.DataFrame(data)
df

company   person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [10]:
df_grouped = df.groupby('company').sum()

In [11]:
df_grouped

person  Sales
company                   
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [27]:
byComp=df.groupby('company')
print(byComp['Sales'].sum())

company
FB      593.0
GOOG    320.0
MSFT    464.0
Name: Sales, dtype: float64


In [26]:
byComp=df.groupby('company')
print(byComp['Sales'].mean())

company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64


In [24]:
df['Sales'] = df['Sales'].astype(float)

In [29]:
df.dtypes

company     object
person      object
Sales      float64
dtype: object

**Concat , Merge and Join**

In [11]:
#creating data frames
df1=pd.DataFrame({'math':[40,67,55,45],
                  'Eng':[56,87,34,56],
                  'Sci':[56,67,89,71],
                  'Chem':[44,59,98,56]},
                 index=['Ravi','Syam','Farhad','Abhi'])
df2=pd.DataFrame({'Math':[50,77,95,74],
                  'Eng':[66,87,34,66],
                  'Sci':[81,87,69,71],
                  'Chem':[56,79,12,34]},
                 index=['shaan','Mahi','Viru','Mona'])
df3=pd.DataFrame({'Math':[67,89,98,56],
                  'Eng':[56,87,89,71],
                  'Chem':[56,79,12,34]},
                 index=['Astha','Rohit','Rahul','Shital'])
print("\ndf1 DataFrame is\n",'-'*50,sep='')
print(df1)
print("\ndf2 DataFrame is\n",'-'*50,sep='')
print(df2)
print("\ndf3 DataFrame is\n",'-'*50,sep='')
print(df3)


df1 DataFrame is
--------------------------------------------------
        math  Eng  Sci  Chem
Ravi      40   56   56    44
Syam      67   87   67    59
Farhad    55   34   89    98
Abhi      45   56   71    56

df2 DataFrame is
--------------------------------------------------
       Math  Eng  Sci  Chem
shaan    50   66   81    56
Mahi     77   87   87    79
Viru     95   34   69    12
Mona     74   66   71    34

df3 DataFrame is
--------------------------------------------------
        Math  Eng  Chem
Astha     67   56    56
Rohit     89   87    79
Rahul     98   89    12
Shital    56   71    34


In [14]:
#concatenation
df_cat1=pd.concat([df1,df2,df3],axis=0)
print(df_cat1)

        math  Eng   Sci  Chem  Math
Ravi    40.0   56  56.0    44   NaN
Syam    67.0   87  67.0    59   NaN
Farhad  55.0   34  89.0    98   NaN
Abhi    45.0   56  71.0    56   NaN
shaan    NaN   66  81.0    56  50.0
Mahi     NaN   87  87.0    79  77.0
Viru     NaN   34  69.0    12  95.0
Mona     NaN   66  71.0    34  74.0
Astha    NaN   56   NaN    56  67.0
Rohit    NaN   87   NaN    79  89.0
Rahul    NaN   89   NaN    12  98.0
Shital   NaN   71   NaN    34  56.0


In [16]:
#concatenation
df_cat2=pd.concat([df1,df2,df3],axis=1)
print(df_cat2)

        math   Eng   Sci  Chem  Math   Eng   Sci  Chem  Math   Eng  Chem
Ravi    40.0  56.0  56.0  44.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Syam    67.0  87.0  67.0  59.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Farhad  55.0  34.0  89.0  98.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Abhi    45.0  56.0  71.0  56.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
shaan    NaN   NaN   NaN   NaN  50.0  66.0  81.0  56.0   NaN   NaN   NaN
Mahi     NaN   NaN   NaN   NaN  77.0  87.0  87.0  79.0   NaN   NaN   NaN
Viru     NaN   NaN   NaN   NaN  95.0  34.0  69.0  12.0   NaN   NaN   NaN
Mona     NaN   NaN   NaN   NaN  74.0  66.0  71.0  34.0   NaN   NaN   NaN
Astha    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  67.0  56.0  56.0
Rohit    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  89.0  87.0  79.0
Rahul    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  98.0  89.0  12.0
Shital   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  56.0  71.0  34.0


In [18]:
df_cat2.fillna(value=0,inplace=True)
df_cat2

math   Eng   Sci  Chem  Math   Eng   Sci  Chem  Math   Eng  Chem
Ravi    40.0  56.0  56.0  44.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Syam    67.0  87.0  67.0  59.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Farhad  55.0  34.0  89.0  98.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Abhi    45.0  56.0  71.0  56.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
shaan    0.0   0.0   0.0   0.0  50.0  66.0  81.0  56.0   0.0   0.0   0.0
Mahi     0.0   0.0   0.0   0.0  77.0  87.0  87.0  79.0   0.0   0.0   0.0
Viru     0.0   0.0   0.0   0.0  95.0  34.0  69.0  12.0   0.0   0.0   0.0
Mona     0.0   0.0   0.0   0.0  74.0  66.0  71.0  34.0   0.0   0.0   0.0
Astha    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  67.0  56.0  56.0
Rohit    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  89.0  87.0  79.0
Rahul    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  98.0  89.0  12.0
Shital   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  56.0  71.0  34.0

**#merging by a common key**

In [33]:
left=pd.DataFrame({'key':['k0','k1','k2','k3'],
    'A':['A0','A1','A2','A3'],
    'B':['B0','B1','B2','B3']})

Right=pd.DataFrame({'key':['k0','k1','k2','k3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']})


In [21]:
left

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [22]:
Right

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k3  C3  D3

In [24]:
merge1=pd.merge(left,Right,how='inner',on='key')
print(merge1)

  key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3


**Join Operators**

In [36]:
leftside=pd.DataFrame({'A':['A0','A1','A2'],
                   'B':['B0','B1','B2']},
                  index=['K0','K1','K2'])
Rightside=pd.DataFrame({'C':['C0','C2','C3'],
                   'D':['D0','D2','D3']},
                  index=['K0','K2','K3'])

In [37]:
leftside

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [38]:
Rightside


C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [39]:
leftside.join(Rightside,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [40]:
leftside.join(Rightside)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

Load .CSV File

In [10]:
import pandas as pd
employee=pd.read_csv('employee data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'employee data.csv'

In [13]:
data=pd.read_csv(r'C:\Users\Samarth Computers\Downloads\employee data.csv')
data.tail()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 14889: invalid start byte

In [ ]:
data.to_csv('path')

In [15]:
excel_file=pd.read_excel(r'C:\Users\Samarth Computers\Downloads\CTC.xlsx')

In [16]:
excel_file.head()

MILLENNIUM ENGINEERS AND CONTRACTORS LTD.  Unnamed: 1          Unnamed: 2  \
0                 COST TO COMPANY STATEMENT         NaN                 NaN   
1                                      NAME         NaN    Sumit D Sanghani   
2                               Designation         NaN  Engineer-Contracts   
3                              Joining Date         NaN                 NaN   
4                                       NaN         NaN             Monthly   

  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6 Unnamed: 7  
0        NaN         NaN         NaN         NaN        NaN  
1        NaN         NaN         NaN         NaN        NaN  
2        NaN         NaN         NaN         NaN        NaN  
3        NaN         NaN         NaN         NaN        NaN  
4     Yearly         NaN         NaN         NaN        NaN

In [17]:
excel_file.tail()

MILLENNIUM ENGINEERS AND CONTRACTORS LTD.  Unnamed: 1   Unnamed: 2  \
31                                       NaN         NaN          NaN   
32                                       NaN         NaN          NaN   
33                                       NaN         NaN          NaN   
34                         Head (HR & Admin)         NaN          NaN   
35                               Place. Pune         NaN  Accepted by   

   Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6 Unnamed: 7  
31        NaN         NaN         NaN         NaN        NaN  
32        NaN         NaN         NaN         NaN          _  
33        NaN         NaN         NaN         NaN        NaN  
34        NaN         NaN         NaN         NaN        NaN  
35        NaN         NaN         NaN         NaN        NaN

In [18]:
type(excel_file)

pandas.core.frame.DataFrame

In [20]:
excel_file.shape

(36, 8)

In [21]:
pd.options.display.max_rows=2

In [24]:
excel_file.head()

MILLENNIUM ENGINEERS AND CONTRACTORS LTD.  Unnamed: 1 Unnamed: 2  \
0                  COST TO COMPANY STATEMENT         NaN        NaN   
..                                       ...         ...        ...   
4                                        NaN         NaN    Monthly   

   Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6 Unnamed: 7  
0         NaN         NaN         NaN         NaN        NaN  
..        ...         ...         ...         ...        ...  
4      Yearly         NaN         NaN         NaN        NaN  

[5 rows x 8 columns]

**Data Cleaning**

In [1]:
import numpy as np
import pandas as pd


In [27]:
vall=np.array([1,np.nan,7,1,8])
vall

array([ 1., nan,  7.,  1.,  8.])

In [ ]:
#Notice that numpy preferred a  native floating-point type for this array.this means that
#unlike the others object arrays,this array supports fast operations pushed into compile code.
#You should be aware that , NaN is bit like- Data Virus -it infects any other objects it touches.
#Regardless of the operation, the result of arithmetic with NaN will be another NaN.

In [29]:
6+np.nan

nan

In [30]:
7*np.nan

nan

In [ ]:
#Numpy does provide some special aggregations that will ignore this missing values

In [31]:
np.nansum(vall)

17.0

In [2]:
#NaN and None are interchangeably where appropriate.
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [9]:
raw_data={'First Name': ['jason',np.nan,'Tina','Jake','Amy','Madhu'],
          'Last Name':['Miller',np.nan,'Ali','Milner','cooze','patil'],
          'age':[42,np.nan,36,24,73,25],
          'sex':['M',np.nan,'F','M','F','F'],
          'Unit-1':[4,np.nan,np.nan,2,3,4],
          'Unit-2':[3,np.nan,np.nan,4,4,4]}
df=pd.DataFrame(raw_data,columns=['First Name','Last Name','age','sex','Unit-1','Unit-2'])
df

First Name Last Name   age  sex  Unit-1  Unit-2
0      jason    Miller  42.0    M     4.0     3.0
1        NaN       NaN   NaN  NaN     NaN     NaN
2       Tina       Ali  36.0    F     NaN     NaN
3       Jake    Milner  24.0    M     2.0     4.0
4        Amy     cooze  73.0    F     3.0     4.0
5      Madhu     patil  25.0    F     4.0     4.0

In [5]:
#drop missing obeservations
df_no_missing=df.dropna()
df_no_missing

First Name Last Name   age sex  Unit-1  Unit-2
0      jason    Miller  42.0   M     4.0     3.0
3       Jake    Milner  24.0   M     2.0     4.0
4        Amy     cooze  73.0   F     3.0     4.0
5      Madhu     patil  25.0   F     4.0     4.0

In [12]:
#drop missing obeservations
df_no_missing=df.dropna(axis=1)
df_no_missing

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [ ]:
#drop rows where all cells in that row is NA

In [6]:
df_cleaned=df.dropna(how='all')
df_cleaned

First Name Last Name   age sex  Unit-1  Unit-2
0      jason    Miller  42.0   M     4.0     3.0
2       Tina       Ali  36.0   F     NaN     NaN
3       Jake    Milner  24.0   M     2.0     4.0
4        Amy     cooze  73.0   F     3.0     4.0
5      Madhu     patil  25.0   F     4.0     4.0

In [13]:
df['Final Score']=np.nan
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0    M     4.0     3.0          NaN
1        NaN       NaN   NaN  NaN     NaN     NaN          NaN
2       Tina       Ali  36.0    F     NaN     NaN          NaN
3       Jake    Milner  24.0    M     2.0     4.0          NaN
4        Amy     cooze  73.0    F     3.0     4.0          NaN
5      Madhu     patil  25.0    F     4.0     4.0          NaN

In [18]:
df.dropna(axis=1,how='all')

First Name Last Name   age  sex  Unit-1  Unit-2
0      jason    Miller  42.0    M     4.0     3.0
1        NaN       NaN   NaN  NaN     NaN     NaN
2       Tina       Ali  36.0    F     NaN     NaN
3       Jake    Milner  24.0    M     2.0     4.0
4        Amy     cooze  73.0    F     3.0     4.0
5      Madhu     patil  25.0    F     4.0     4.0

In [16]:
df.fillna(0)

First Name Last Name   age sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0   M     4.0     3.0          0.0
1          0         0   0.0   0     0.0     0.0          0.0
2       Tina       Ali  36.0   F     0.0     0.0          0.0
3       Jake    Milner  24.0   M     2.0     4.0          0.0
4        Amy     cooze  73.0   F     3.0     4.0          0.0
5      Madhu     patil  25.0   F     4.0     4.0          0.0

In [22]:
df["Unit-1"].fillna(df["Unit-1"].mean(),inplace=True)
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0    M    4.00     3.0          NaN
1        NaN       NaN   NaN  NaN    3.25     NaN          NaN
2       Tina       Ali  36.0    F    3.25     NaN          NaN
3       Jake    Milner  24.0    M    2.00     4.0          NaN
4        Amy     cooze  73.0    F    3.00     4.0          NaN
5      Madhu     patil  25.0    F    4.00     4.0          NaN

In [23]:
df["Unit-2"].fillna(df.groupby("sex")["Unit-2"].transform("mean"),inplace=True)
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0    M    4.00     3.0          NaN
1        NaN       NaN   NaN  NaN    3.25     NaN          NaN
2       Tina       Ali  36.0    F    3.25     4.0          NaN
3       Jake    Milner  24.0    M    2.00     4.0          NaN
4        Amy     cooze  73.0    F    3.00     4.0          NaN
5      Madhu     patil  25.0    F    4.00     4.0          NaN

In [24]:
#select some rows but ignore the missing data points
df[df['age'].notnull() & df['sex'].notnull()]

First Name Last Name   age sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0   M    4.00     3.0          NaN
2       Tina       Ali  36.0   F    3.25     4.0          NaN
3       Jake    Milner  24.0   M    2.00     4.0          NaN
4        Amy     cooze  73.0   F    3.00     4.0          NaN
5      Madhu     patil  25.0   F    4.00     4.0          NaN

In [34]:
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0    M    4.00     3.0          NaN
1        NaN       NaN   NaN  NaN    3.25     NaN          NaN
2       Tina       Ali  36.0    F    3.25     4.0          NaN
3       Jake    Milner  24.0    M    2.00     4.0          NaN
4        Amy     cooze  73.0    F    3.00     4.0          NaN
5      Madhu     patil  25.0    F    4.00     4.0          NaN

In [38]:
df.fillna(method='bfill')

C:\Users\Samarth Computers\AppData\Local\Temp\ipykernel_120\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


First Name Last Name   age sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0   M    4.00     3.0          NaN
1       Tina       Ali  36.0   F    3.25     4.0          NaN
2       Tina       Ali  36.0   F    3.25     4.0          NaN
3       Jake    Milner  24.0   M    2.00     4.0          NaN
4        Amy     cooze  73.0   F    3.00     4.0          NaN
5      Madhu     patil  25.0   F    4.00     4.0          NaN

In [39]:
df.fillna(method='ffill')

C:\Users\Samarth Computers\AppData\Local\Temp\ipykernel_120\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


First Name Last Name   age sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0   M    4.00     3.0          NaN
1      jason    Miller  42.0   M    3.25     3.0          NaN
2       Tina       Ali  36.0   F    3.25     4.0          NaN
3       Jake    Milner  24.0   M    2.00     4.0          NaN
4        Amy     cooze  73.0   F    3.00     4.0          NaN
5      Madhu     patil  25.0   F    4.00     4.0          NaN

In [45]:
df["Final Score"].fillna(df["Unit-1"]+df["Unit-2"],inplace=True)
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score
0      jason    Miller  42.0    M    4.00     3.0         7.00
1        NaN       NaN   NaN  NaN    3.25     NaN          NaN
2       Tina       Ali  36.0    F    3.25     4.0         7.25
3       Jake    Milner  24.0    M    2.00     4.0         6.00
4        Amy     cooze  73.0    F    3.00     4.0         7.00
5      Madhu     patil  25.0    F    4.00     4.0         8.00

In [47]:
df['location']='Bengaluru'
df

First Name Last Name   age  sex  Unit-1  Unit-2  Final Score   location
0      jason    Miller  42.0    M    4.00     3.0         7.00  Bengaluru
1        NaN       NaN   NaN  NaN    3.25     NaN          NaN  Bengaluru
2       Tina       Ali  36.0    F    3.25     4.0         7.25  Bengaluru
3       Jake    Milner  24.0    M    2.00     4.0         6.00  Bengaluru
4        Amy     cooze  73.0    F    3.00     4.0         7.00  Bengaluru
5      Madhu     patil  25.0    F    4.00     4.0         8.00  Bengaluru

**Hierarchical Indexing**

In [ ]:
#3d,4d data= Pane1 and Pane14D

In [25]:
raw_data={'Company': ['Google','Google','Google','Google','Facebook','Facebook','Facebook','Facebook','Amazon','Amazon','Amazon','Amazon'],
          'Project':['1st','1st','2nd','2nd','1st','1st','2nd','2nd','1st','1st','2nd','2nd'],
          'Incharge':['Sundar','Ruth','Benjamin','Sergey','Mark','Shery','Eduardo','David','Jeffrey','Andy','Keith','Edith'],
          'Sales(in Millions)':[54,24,31,12,23,24,34,31,32,23,52,13],
          'Profit(in Millions)':[14,8,9,4,10,11,14,13,12,7,22,4]}
df=pd.DataFrame(raw_data,columns=['Company', 'Project','Incharge','Sales(in Millions)','Profit(in Millions)'])
df

Company Project  Incharge  Sales(in Millions)  Profit(in Millions)
0     Google     1st    Sundar                  54                   14
1     Google     1st      Ruth                  24                    8
2     Google     2nd  Benjamin                  31                    9
3     Google     2nd    Sergey                  12                    4
4   Facebook     1st      Mark                  23                   10
5   Facebook     1st     Shery                  24                   11
6   Facebook     2nd   Eduardo                  34                   14
7   Facebook     2nd     David                  31                   13
8     Amazon     1st   Jeffrey                  32                   12
9     Amazon     1st      Andy                  23                    7
10    Amazon     2nd     Keith                  52                   22
11    Amazon     2nd     Edith                  13                    4

In [11]:
#set hierarchical index but leave the columns inplace
df.set_index(['Company','Project'],drop=False)

Company Project  Incharge  Sales(in Millions)  \
Company  Project                                                   
Google   1st        Google     1st    Sundar                  54   
         1st        Google     1st      Ruth                  24   
         2nd        Google     2nd  Benjamin                  31   
         2nd        Google     2nd    Sergey                  12   
Facebook 1st      Facebook     1st      Mark                  23   
         1st      Facebook     1st     Shery                  24   
         2nd      Facebook     2nd   Eduardo                  34   
         2nd      Facebook     2nd     David                  31   
Amazon   1st        Amazon     1st   Jeffrey                  32   
         1st        Amazon     1st      Andy                  23   
         2nd        Amazon     2nd     Keith                  52   
         2nd        Amazon     2nd     Edith                  13   

                  Profit(in Millions)  
Company  Project                       
Google   1st                       14  
         1st                        8  
         2nd                        9  
         2nd                        4  
Facebook 1st                       10  
         1st                       11  
         2nd                       14  
         2nd                       13  
Amazon   1st                       12  
         1st                        7  
         2nd                       22  
         2nd                        4

In [16]:
#set hierarchical index but leave the columns inplace
df.set_index(['Company','Project'],drop=True)

Incharge  Sales(in Millions)  Profit(in Millions)
Company  Project                                                   
Google   1st        Sundar                  54                   14
         1st          Ruth                  24                    8
         2nd      Benjamin                  31                    9
         2nd        Sergey                  12                    4
Facebook 1st          Mark                  23                   10
         1st         Shery                  24                   11
         2nd       Eduardo                  34                   14
         2nd         David                  31                   13
Amazon   1st       Jeffrey                  32                   12
         1st          Andy                  23                    7
         2nd         Keith                  52                   22
         2nd         Edith                  13                    4

In [24]:
#set hierarchy =first by company then by project
df.set_index(['Company','Project'],inplace=False)

Incharge  Sales(in Millions)  Profit(in Millions)
Company  Project                                                   
Google   1st        Sundar                  54                   14
         1st          Ruth                  24                    8
         2nd      Benjamin                  31                    9
         2nd        Sergey                  12                    4
Facebook 1st          Mark                  23                   10
         1st         Shery                  24                   11
         2nd       Eduardo                  34                   14
         2nd         David                  31                   13
Amazon   1st       Jeffrey                  32                   12
         1st          Andy                  23                    7
         2nd         Keith                  52                   22
         2nd         Edith                  13                    4

In [21]:
#swap the levels in the index
df.swaplevel('Company','Project')

Incharge  Sales(in Millions)  Profit(in Millions)
Project Company                                                    
1st     Google      Sundar                  54                   14
        Google        Ruth                  24                    8
2nd     Google    Benjamin                  31                    9
        Google      Sergey                  12                    4
1st     Facebook      Mark                  23                   10
        Facebook     Shery                  24                   11
2nd     Facebook   Eduardo                  34                   14
        Facebook     David                  31                   13
1st     Amazon     Jeffrey                  32                   12
        Amazon        Andy                  23                    7
2nd     Amazon       Keith                  52                   22
        Amazon       Edith                  13                    4

In [30]:
#Summarize the results by Comapny
df.groupby('Company').sum()

Project                  Incharge  Sales(in Millions)  \
Company                                                                
Amazon    1st1st2nd2nd     JeffreyAndyKeithEdith                 120   
Facebook  1st1st2nd2nd     MarkSheryEduardoDavid                 112   
Google    1st1st2nd2nd  SundarRuthBenjaminSergey                 121   

          Profit(in Millions)  
Company                        
Amazon                     45  
Facebook                   48  
Google                     35

In [31]:
#Summarize the results by Project
df.groupby('Project').sum()

Company  \
Project                                             
1st      GoogleGoogleFacebookFacebookAmazonAmazon   
2nd      GoogleGoogleFacebookFacebookAmazonAmazon   

                                     Incharge  Sales(in Millions)  \
Project                                                             
1st            SundarRuthMarkSheryJeffreyAndy                 180   
2nd      BenjaminSergeyEduardoDavidKeithEdith                 173   

         Profit(in Millions)  
Project                       
1st                       62  
2nd                       66

In [4]:
#Data Manipulation
#define a function
import pandas as pd
def salary_hike(x):
    if (x>3000):
        return np.ceil(x+(x*0.30))
    else:
        return np.ceil(x*1.5)

In [6]:
df=pd.DataFrame({'Dept':[1,2,3,4,5,6,7,8,9,10],
                 'Emp Name':['Rajesh','Shankar','Sindhu','Akshay','Vivaan','Monika','Salman','Aisha','Remo','Amit'],
                 'Salary':[4944,5455,6166,4044,3433,2922,6466,7977,6766,5155]})
df

Dept Emp Name  Salary
0     1   Rajesh    4944
1     2  Shankar    5455
2     3   Sindhu    6166
3     4   Akshay    4044
4     5   Vivaan    3433
5     6   Monika    2922
6     7   Salman    6466
7     8    Aisha    7977
8     9     Remo    6766
9    10     Amit    5155

In [8]:
df['New Salary']=df['Salary'].apply(salary_hike)
print(df)

   Dept Emp Name  Salary  New Salary
0     1   Rajesh    4944      6428.0
1     2  Shankar    5455      7092.0
2     3   Sindhu    6166      8016.0
3     4   Akshay    4044      5258.0
4     5   Vivaan    3433      4463.0
5     6   Monika    2922      4383.0
6     7   Salman    6466      8406.0
7     8    Aisha    7977     10371.0
8     9     Remo    6766      8796.0
9    10     Amit    5155      6702.0


In [11]:
df['Name_Length']=df['Emp Name'].apply(len)
df

Dept Emp Name  Salary  New Salary  Name_Length
0     1   Rajesh    4944      6428.0            6
1     2  Shankar    5455      7092.0            7
2     3   Sindhu    6166      8016.0            6
3     4   Akshay    4044      5258.0            6
4     5   Vivaan    3433      4463.0            6
5     6   Monika    2922      4383.0            6
6     7   Salman    6466      8406.0            6
7     8    Aisha    7977     10371.0            5
8     9     Remo    6766      8796.0            4
9    10     Amit    5155      6702.0            4

In [16]:
df['New Salary'].apply(lambda x:np.sqrt(x))
df

Dept Emp Name  Salary  New Salary  Name_Length
0     1   Rajesh    4944      6428.0            6
1     2  Shankar    5455      7092.0            7
2     3   Sindhu    6166      8016.0            6
3     4   Akshay    4044      5258.0            6
4     5   Vivaan    3433      4463.0            6
5     6   Monika    2922      4383.0            6
6     7   Salman    6466      8406.0            6
7     8    Aisha    7977     10371.0            5
8     9     Remo    6766      8796.0            4
9    10     Amit    5155      6702.0            4

In [17]:
print(df['New Salary'].sum())

69915.0


In [18]:
print(df['New Salary'].min())

4383.0


In [19]:
print(df['New Salary'].max())

10371.0


In [20]:
print(df.columns)

Index(['Dept', 'Emp Name', 'Salary', 'New Salary', 'Name_Length'], dtype='object')


In [21]:
l=list(df.columns)
print(l)

['Dept', 'Emp Name', 'Salary', 'New Salary', 'Name_Length']


In [22]:
del df['Salary']

In [23]:
df

Dept Emp Name  New Salary  Name_Length
0     1   Rajesh      6428.0            6
1     2  Shankar      7092.0            7
2     3   Sindhu      8016.0            6
3     4   Akshay      5258.0            6
4     5   Vivaan      4463.0            6
5     6   Monika      4383.0            6
6     7   Salman      8406.0            6
7     8    Aisha     10371.0            5
8     9     Remo      8796.0            4
9    10     Amit      6702.0            4

In [24]:
df.sort_values(by='New Salary')

Dept Emp Name  New Salary  Name_Length
5     6   Monika      4383.0            6
4     5   Vivaan      4463.0            6
3     4   Akshay      5258.0            6
0     1   Rajesh      6428.0            6
9    10     Amit      6702.0            4
1     2  Shankar      7092.0            7
2     3   Sindhu      8016.0            6
6     7   Salman      8406.0            6
8     9     Remo      8796.0            4
7     8    Aisha     10371.0            5

In [26]:
df.sort_values(by='New Salary',ascending=False)

Dept Emp Name  New Salary  Name_Length
7     8    Aisha     10371.0            5
8     9     Remo      8796.0            4
6     7   Salman      8406.0            6
2     3   Sindhu      8016.0            6
1     2  Shankar      7092.0            7
9    10     Amit      6702.0            4
0     1   Rajesh      6428.0            6
3     4   Akshay      5258.0            6
4     5   Vivaan      4463.0            6
5     6   Monika      4383.0            6

In [2]:
#Series Manipulation
import numpy as np
import pandas as pd

In [29]:
#we can given our own serial names to column
ser1=pd.Series(data=[1,2,3,4],index=['CA','OR','CO','AZ'])
#PANDAS WILL UNDERSTAND 1ST IS DATA AND 2ND IS SERIES, NO NEED TO WRITE
ser2=pd.Series([1,2,5,4],['CA','OR','NV','AZ'])

In [30]:
ser2

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [31]:
ser1

CA    1
OR    2
CO    3
AZ    4
dtype: int64

In [34]:
print("\nindexing by name of the item\n",'-'*50,sep='')
print(ser1['CA'])
print(ser1['AZ'])
print(ser2['NV'])


indexing by name of the item
--------------------------------------------------
1
4
5


In [36]:
#FETCH ELEMENTS THROUGH POSITIONAL INDEX
print(ser1.iloc[0])

1


In [37]:
#indexing by a range
print(ser1[1:4],sep='')

OR    2
CO    3
AZ    4
dtype: int64


In [38]:
ser3=ser2+ser1
ser3

AZ    8.0
CA    2.0
CO    NaN
NV    NaN
OR    4.0
dtype: float64

In [39]:
#extended data frame manipulation
import numpy as np
import pandas as pd

In [3]:
matrix_data=np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels=['Raju','Pandey','Srini','Sunil','Ashok']
column_headings=['age','height','weight']

In [4]:
print(type(matrix_data))

<class 'numpy.matrix'>


In [5]:
df=pd.DataFrame(data=matrix_data,index=row_labels,columns=column_headings)
print("\nA new dataframe\n",'-'*55,sep='')
print(df)


A new dataframe
-------------------------------------------------------
        age  height  weight
Raju     22      66     140
Pandey   42      70     148
Srini    30      62     125
Sunil    35      68     160
Ashok    25      62     152


In [48]:
print("\nPrint columns\n",'-'*55,sep='')
print(df[['height','weight']])


Print columns
-------------------------------------------------------
        height  weight
Raju        66     140
Pandey      70     148
Srini       62     125
Sunil       68     160
Ashok       62     152


In [44]:
print("\nType of the column\n",'-'*55,sep='')
print(type(df['height']))


Type of the column
-------------------------------------------------------
<class 'pandas.core.series.Series'>


In [45]:
print(df.age)  #dot method only one column can be access at a single time

Raju      22
Pandey    42
Srini     30
Sunil     35
Ashok     25
Name: age, dtype: int32


In [49]:
#slicing
df.loc['Raju']

age        22
height     66
weight    140
Name: Raju, dtype: int32

In [50]:
df.iloc[0]

age        22
height     66
weight    140
Name: Raju, dtype: int32

In [52]:
df.loc['Raju','height']

66

In [53]:
df.loc['Raju',['height','weight']]

height     66
weight    140
Name: Raju, dtype: int32

In [54]:
df.loc[['Srini','Sunil'],['height','weight']]

height  weight
Srini      62     125
Sunil      68     160

In [6]:
df.loc['Ashok',['height','weight']]

height     62
weight    152
Name: Ashok, dtype: int32

In [7]:
#select data on condition
print(df[df['height']>65])

        age  height  weight
Raju     22      66     140
Pandey   42      70     148
Sunil    35      68     160


In [8]:
booldf1=df['height']>65
booldf2=df['weight']>145
print(df[(booldf1) & (booldf2)])

        age  height  weight
Pandey   42      70     148
Sunil    35      68     160


In [9]:
print(df[(df['height']>65) & (df['weight']>145)])

        age  height  weight
Pandey   42      70     148
Sunil    35      68     160


In [10]:
print(df[booldf1][['age','weight']])

        age  weight
Raju     22     140
Pandey   42     148
Sunil    35     160


In [11]:
print(df.reset_index())

    index  age  height  weight
0    Raju   22      66     140
1  Pandey   42      70     148
2   Srini   30      62     125
3   Sunil   35      68     160
4   Ashok   25      62     152


In [13]:
df=df[df['age']<35]
df

age  height  weight
Raju    22      66     140
Srini   30      62     125
Ashok   25      62     152

In [14]:
print(df.reset_index(drop=True))

   age  height  weight
0   22      66     140
1   30      62     125
2   25      62     152


In [16]:
df['Profession']="Student Teacher Engineer".split()
print(df)

       age  height  weight Profession
Raju    22      66     140    Student
Srini   30      62     125    Teacher
Ashok   25      62     152   Engineer


In [17]:
print(df.set_index('Profession'))

            age  height  weight
Profession                     
Student      22      66     140
Teacher      30      62     125
Engineer     25      62     152


***Date Time Manipulation**

In [18]:
import numpy as np
import pandas as pd

In [26]:
date_range=pd.date_range('4/12/2021',periods=6)   #DATE WILL KEEP CHANGING
dates=pd.DataFrame(date_range,columns=['Date'])

In [27]:
dates

Date
0 2021-04-12
1 2021-04-13
2 2021-04-14
3 2021-04-15
4 2021-04-16
5 2021-04-17

In [28]:
date_range=pd.date_range('4/12/2021',periods=12,freq='M')  #MONTH WILL KEEP CHANGING
dates=pd.DataFrame(date_range,columns=['Date'])
dates

Date
0  2021-04-30
1  2021-05-31
2  2021-06-30
3  2021-07-31
4  2021-08-31
5  2021-09-30
6  2021-10-31
7  2021-11-30
8  2021-12-31
9  2022-01-31
10 2022-02-28
11 2022-03-31

In [29]:
date_range=pd.date_range('4/12/2021',periods=12,freq='Y')  #YEAR WILL KEEP CHANGEING
dates=pd.DataFrame(date_range,columns=['Date'])
dates

Date
0  2021-12-31
1  2022-12-31
2  2023-12-31
3  2024-12-31
4  2025-12-31
5  2026-12-31
6  2027-12-31
7  2028-12-31
8  2029-12-31
9  2030-12-31
10 2031-12-31
11 2032-12-31

In [21]:
dates['Day']=dates['Date'].dt.day
dates['Month']=dates['Date'].dt.month
dates['Year']=dates['Date'].dt.year
dates

Date  Day  Month  Year
0 2021-04-12   12      4  2021
1 2021-04-13   13      4  2021
2 2021-04-14   14      4  2021
3 2021-04-15   15      4  2021
4 2021-04-16   16      4  2021
5 2021-04-17   17      4  2021

In [22]:
dates=pd.date_range('1/1/2000',periods=7)
ts=pd.Series(np.arange(7),index=dates)
print(ts)

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32


In [34]:
#Export your file where ever you want
ts.to_csv(r"C:\Users\Samarth Computers\Downloads\date data.csv")

In [38]:
daterange=pd.date_range('2021/9/21',periods=6)
dates=pd.DataFrame(daterange,columns=['Date'])
dates

Date
0 2021-09-21
1 2021-09-22
2 2021-09-23
3 2021-09-24
4 2021-09-25
5 2021-09-26

**SQLLite DBMS**

In [1]:
import sqlite3

In [2]:
dbcon=sqlite3.connect("Student_Database.db")

In [3]:
cur=dbcon.cursor()

In [4]:
cur.execute("Create table student(id int primary key,name text,age int)")

OperationalError: table student already exists

In [5]:
cur.execute("insert into student(id,name,age) values(1,'smith',11)")
cur.execute("insert into student(id,name,age) values(2,'sam',40)")
cur.execute("insert into student(id,name,age) values(3,'Charles',19)")
cur.execute("insert into student(id,name,age) values(4,'Remo',25)")

In [6]:
dbcon.commit;

In [7]:
rows=cur.execute("select* from student")

for row in rows:
    print(row)

(1, 'smith', 11)
(2, 'sam', 40)
(3, 'Charles', 19)
(4, 'Remo', 25)
